### ISSUE TITLE
White screen when running emulator or real device

### ISSUE THREAD

**Issue by Fireballlion** [llSourcell/How_to_Build_a_healthcare_startup#10]
Hi.
I have downloaded the repo but when i run it in my android studio ,v3.5, all i get in my emulator/real device is a white screen when opening the app and the console just says "E/BpSurfaceComposerClient(10222): Failed to transact (-1)
 E/BpSurfaceComposerClient(10222): Failed to transact (-1)"
. I have the same problem with the flutter-realtime-detection-master by shaqian. Any help with this would be greatly appreciated.

**Comment by Fireballlion** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Note: C:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_tts-0.2.6\android\src\main\java\com\tundralabs\fluttertts\FlutterTtsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\tflite-1.0.4\android\src\main\java\sq\flutter\tflite\TflitePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/TextToSpeech( 7435): Sucessfully bound to com.google.android.tts
Syncing files to device Android SDK built for x86...
I/zygote  ( 7435): Do partial code cache collection, code=30KB, data=17KB
I/zygote  ( 7435): After code cache collection, code=26KB, data=16KB
I/zygote  ( 7435): Increasing code cache capacity to 128KB
D/OpenGLRenderer( 7435): HWUI GL Pipeline
I/OpenGLRenderer( 7435): Initialized EGL, version 1.4
D/OpenGLRenderer( 7435): Swap behavior 1
D/        ( 7435): HostConnection::get() New Host Connection established 0xca837440, tid 7521
W/OpenGLRenderer( 7435): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 7435): Swap behavior 0
D/EGL_emulation( 7435): eglCreateContext: 0xde942ce0: maj 3 min 1 rcv 4
D/EGL_emulation( 7435): eglMakeCurrent: 0xde942ce0: ver 3 1 (tinfo 0xca4479f0)
E/eglCodecCommon( 7435): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 7435): glUtilsParamSize: unknow param 0x000082da
D/        ( 7435): HostConnection::get() New Host Connection established 0xe031c580, tid 7485
D/EGL_emulation( 7435): eglCreateContext: 0xe03052a0: maj 3 min 1 rcv 4
D/EGL_emulation( 7435): eglMakeCurrent: 0xe03052a0: ver 3 1 (tinfo 0xe0303360)
E/eglCodecCommon( 7435): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 7435): glUtilsParamSize: unknow param 0x000082da
E/flutter ( 7435): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 7435): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter ( 7435): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter ( 7435): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
E/flutter ( 7435): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
E/flutter ( 7435): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter ( 7435): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter ( 7435): <asynchronous suspension>
E/flutter ( 7435): #4      availableCameras (package:camera/camera.dart:56:24)
E/flutter ( 7435): <asynchronous suspension>
E/flutter ( 7435): #5      main (package:flutter_realtime_detection/main.dart:10:21)
E/flutter ( 7435): <asynchronous suspension>
E/flutter ( 7435): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter ( 7435): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7435): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7435): #9      _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 7435): #10     runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 7435): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter ( 7435): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 7435): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 7435): 
D/EGL_emulation( 7435): eglMakeCurrent: 0xde942ce0: ver 3 1 (tinfo 0xca4479f0)
I/TextToSpeech( 7435): Connected to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
I/TextToSpeech( 7435): Set up connection to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
I/zygote  ( 7435): Do partial code cache collection, code=60KB, data=39KB
I/zygote  ( 7435): After code cache collection, code=60KB, data=39KB
I/zygote  ( 7435): Increasing code cache capacity to 256KB

This is the full console output, thank you.
