### ISSUE TITLE
facing FileNotFoundException on clicking "Begin" button

### ISSUE THREAD

**Issue by 1207roy** [llSourcell/How_to_Build_a_healthcare_startup#13]
E/flutter ( 8791): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed, null)
E/flutter ( 8791): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 8791): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 8791): <asynchronous suspension>
E/flutter ( 8791): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 8791): #3      Tflite.loadModel (package:tflite/tflite.dart:15:27)
E/flutter ( 8791): #4      ThirdRoute.loadModel (package:flutter_realtime_detection/home.dart:46:28)
E/flutter ( 8791): #5      ThirdRoute.onSelect (package:flutter_realtime_detection/home.dart:65:5)
E/flutter ( 8791): #6      ThirdRoute.build.<anonymous closure> (package:flutter_realtime_detection/home.dart:114:40)
E/flutter ( 8791): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:14)
E/flutter ( 8791): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 8791): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 8791): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 8791): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 8791): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 8791): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter ( 8791): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 8791): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 8791): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 8791): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 8791): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 8791): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 8791): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 8791): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8791): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8791): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8791): #24     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 8791): #25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 8791): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 8791): #27     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 8791): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter ( 8791):

**Comment by hritik7080** [comment]
Hey  @1207roy ,
I am also getting the same issue, have you found any solution for this?
